#
#Secret Name: drupal-mysql-secret
#Secret: MYSQL_ROOT_PASSWORD=root_password
#Secret: MYSQL_DATABASE=drupal-database
#Secret: MYSQL_USER=root 

---
apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
data:
   MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
   MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl
   MYSQL_USER: cm9vdA== 
type: Opaque
