#Claim Name: drupal-pvc
#Storage Request: 5Gi
#Access modes: ReadWriteOnce 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: drupal-pvc
   labels:
     app: drupal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   
